---
title: "Script"
author: "Kathryn Denning, Karlena Ochoa, Jenn Lewis, Tamara Niella"
date: "5/14/2019"
output: html_document
---

```{r setup}
library(tidyverse)
library(rio)
library(here)
library(stringr)

data <- import(here("data", "movie_metadata.csv_movie_metadata.csv"))

data <- data %>%
  mutate(gross = as.numeric(gross),
         budget = as.numeric(budget),
         profit = gross-budget)
```

```{r Custom Function 1}
#Make a function that tells you the average imdb rating for a specfic actor; this function will only work within this data set

average_imdb <- function(x) {
 df <- aggregate(imdb_score ~ actor_1_name, data, mean)
 
 row.names(df) <- df$actor_1_name 
 
 df[x,"imdb_score"]
    }

#Test function, provide actor name in quotes to get their average imdb_score

average_imdb("Tom Cruise")
average_imdb("Johnny Depp")
average_imdb("Will Smith")

```
```{r Custom Function 2}
#Create a custom function that will pull out descriptive statistics for a variable

descriptives <- function(x) {
  data.frame(mean(x), sd(x), min(x), max(x), length(x))
  }

#Test if it works
descriptives(data$imdb_score)
```

```{r}

# let's nest our data by genre

df_genre <- data %>% 
  group_by(genres)%>%
  nest()

# let's nest our data by country 

df_country <- data %>% 
  drop_na()%>%
  group_by(country)%>%
  nest()

# Country seems to be a more reasonable grouping variable to work with - In genres there seems to be a lot of combinations of different genres - however, there are countries with too few observations, so it might be 

```

